### ISSUE TITLE
Subscribe while disconnected

### ISSUE THREAD

**Issue by pgroen** [TrueBrain/TrueMQTT-cpp#10]
https://github.com/TrueBrain/TrueMQTT-cpp/blob/31ddd2c76d6b5202e8f40b4532e112c85c5f8269/src/Client.cpp#L135

As you return when there is no connection, does that mean that there is no a-sync behaviour?

**Comment by TrueBrain** [comment]
Depends on your definitions of async, I guess. But that is not really your question ofc :D

Currently the library forces you to do a `connect` before any publish/subscribe (see notes in interface description). After connect, it will make sure the request gets executes whenever the actual connection is made, and recreates subscriptions after an automatic reconnect.

The reason to demand a connect first, is purely to ensure that after a call to the `disconnect` function, all state is cleared and remains cleared.

Basically, I didn't see a usecase where you would want to subscribe or publish something before calling `connect`.

Additionally, current the library is non-blocking when there isn't a connection with the broker, and somewhat blocking when there is. The latter is something that needs a bit of improving, as `send` is currently executed from the main thread, and not from the connection thread. This normally isn't blocking, but during congestion it might stall. So that needs fixing to make the function truly non-blocking.

Does that make the function async? Well, that is a manner of opinion I guess :D Given `subscribe` doesn't return any value, it is not async in the sense of "a promise", but it is async in the sense of non-blocking. Basically, QoS 0 only, also on the interface itself :D
